# Generated by Django 6.0 on 2025-12-11 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicant',
            unique_together={('applied_job', 'email'), ('applied_job', 'phone')},
        ),
    ]
